[versions]

compileSdkVersion = "33"
minSdkVersion = "26"
targetSdkVersion = "33"
versionCode = "1"
versionName = "1.0"

hilt = "2.44.2"
gson = "2.10"
room = "2.4.3"
ktor = "1.6.8"
glide = "4.14.2"
material="1.7.0"
paging = "3.1.1"
kotlin = "1.7.21"
fragment = "1.5.4"
retrofit = "2.9.0"
lifecycle = "2.5.1"
coroutines = "1.6.4"
androidxCore = "1.9.0"
gradlePlugin = "7.3.1"
navigation = "2.5.3"
okHttp = "5.0.0-alpha.10"
glideWebDecoder = "2.2.4.13.2"
junit = "4.13.2"
mockito = "3.8.0"
robolectric = "4.9"

[plugins]
android-application = { id = "com.android.application", version.ref = "gradlePlugin" }
android-library = { id = "com.android.library", version.ref = "gradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
google-service = { id = "com.google.gms.google-services", version = "4.3.14" }

[libraries]

google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
google-hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-test = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

javax-inject = { module = "javax.inject:javax.inject", version = "1" }

kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

androidx-core = { module = "androidx.core:core-ktx", version = "1.9.0" }
androidx-compat = { module = "androidx.appcompat:appcompat", version = "1.5.1" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-paging-common = { module = "androidx.paging:paging-common", version.ref = "paging" }
androidx-paging-runtime = { module = "androidx.paging:paging-runtime-ktx", version.ref = "paging" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-lifecycle-viewmodel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation" }
androidx-room = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

androidx-text-junit = { module = "androidx.test.ext:junit", version = "1.1.4" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.0" }
androidx-test-espresso-contrib = { module = "androidx.test.espresso:espresso-contrib", version = "3.5.0" }
androidx-test-arch-core = { module = "androidx.arch.core:core-testing", version = "2.1.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.5.1" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.5.0"}
androidx-test-junit = { module = "androidx.test.ext:junit-ktx", version = "1.1.4" }
androidx-test-fragment = { module = "androidx.fragment:fragment-testing", version = "1.5.4" }

squareup-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
squareup-retrofit-gson-converter = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
squareup-retrofit-scalars-converter = { module = "com.squareup.retrofit2:converter-scalars", version.ref = "retrofit" }
squareup-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okHttp" }
squareup-okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okHttp" }

ktor-gson = { module = "io.ktor:ktor-client-gson", version.ref = "ktor" }
ktor-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-logging = { module = "io.ktor:ktor-client-logging-jvm", version.ref = "ktor" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-webdecoder = { module = "com.github.zjupure:webpdecoder", version.ref = "glideWebDecoder" }

junit = { module = "junit:junit", version.ref = "junit" }
robolectric = { module = "org.robolectric:robolectric", version.ref = "robolectric" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-android = { module = "org.mockito:mockito-android", version.ref = "mockito" }